{
  "robot_name": "skeleton_torque_suit_passive_cable",
  "simulator": "newton",
  "num_envs": 4096,
  "batch_size": 16384,
  "motion_file": "data/motion_for_trackers/skeleton_torque_suit_motions14.pt",
  "experiment_path": "examples/experiments/mimic/mlp_motions14_suit_newton.py",
  "experiment_name": "mimic_suit_passive_cable_motions14_23dof",
  "save_dir": "tasks/mimic_suit_passive_cable_motions14_23dof/output_newton_fd03",
  "scenes_file": null,
  "checkpoint": "tasks/mimic_suit_passive_cable_motions14_23dof/output_newton/last.ckpt",
  "checkpoint_dir": null,
  "use_wandb": false,
  "use_slurm": false,
  "ngpu": 1,
  "nodes": 1,
  "headless": true,
  "seed": 0,
  "torch_deterministic": false,
  "training_max_steps": 10000000000000,
  "overrides": [],
  "create_config_only": false,
  "wandb_id": null
}